# Generated by Django 3.0 on 2020-01-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='friendss',
            new_name='friends',
        ),
    ]
