# Generated by Django 3.0 on 2020-01-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200120_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorite_book',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hobby',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
