# Generated by Django 3.0 on 2020-01-20 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(default=uuid.UUID('f6fc3649-dba5-4a9e-b1d0-8f7e1fa068cb')),
        ),
    ]
