# Generated by Django 3.0 on 2020-01-20 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200120_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(default=uuid.UUID('a657d120-71be-4fd6-9680-6098f180aac9')),
        ),
    ]
