# Generated by Django 3.0 on 2020-01-20 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200120_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(default=uuid.UUID('2951497e-9e80-44db-9b2d-92d1a5f76d80')),
        ),
    ]
