# Generated by Django 3.0 on 2020-01-20 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200120_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(default=uuid.UUID('61d6b7bb-fb21-4b1c-8335-ef517dbb3076')),
        ),
    ]
