# Generated by Django 3.0 on 2020-01-20 02:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200120_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(default=uuid.UUID('29745d96-2813-4666-b986-513f6e67c892')),
        ),
    ]
