# Generated by Django 3.0 on 2020-01-20 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200120_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(default=uuid.UUID('d83454b6-5baf-4e9e-99d6-32c4e74cb28c')),
        ),
    ]
