# Generated by Django 3.0 on 2020-01-20 02:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200120_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(default=uuid.UUID('f1ceedb0-f343-4ab4-b7be-b136ee2bdd02')),
        ),
    ]
