# Generated by Django 3.0 on 2020-01-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200120_1241'),
        ('chat', '0011_auto_20200120_1158'),
    ]

    operations = [
    ]
